-- Matchday World Tour – Seed Places Data
-- Covers all 11 FIFA 2026 U.S. host cities

INSERT INTO places (city_id, name, type, description, address, maps_url, affiliate_url, tags)
VALUES

-- =========================
-- NEW YORK / NEW JERSEY
-- =========================
((SELECT id FROM cities WHERE slug = 'new-york-new-jersey'),
 'Legends NYC',
 'bar',
 'Massive sports bar near MSG with wall-to-wall screens and a lively matchday atmosphere.',
 '6 W 33rd St, New York, NY 10001',
 'https://maps.google.com/?q=Legends+NYC+6+W+33rd+St',
 null,
 '["sports bar","big screens","soccer","midtown"]'),

((SELECT id FROM cities WHERE slug = 'new-york-new-jersey'),
 'Smithfield Hall',
 'bar',
 'Premier soccer bar in NYC with an international fan atmosphere and all major leagues shown.',
 '138 W 25th St, New York, NY 10001',
 'https://maps.google.com/?q=Smithfield+Hall+138+W+25th+St',
 null,
 '["soccer pub","fan zone","international","chelsea"]'),

((SELECT id FROM cities WHERE slug = 'new-york-new-jersey'),
 'Nevada Smiths',
 'bar',
 'New York''s original soccer bar, open since 1995 with passionate fans from every nation.',
 '74 3rd Ave, New York, NY 10003',
 'https://maps.google.com/?q=Nevada+Smiths+74+3rd+Ave',
 null,
 '["soccer","historic","east village","fan culture"]'),

((SELECT id FROM cities WHERE slug = 'new-york-new-jersey'),
 'Katz''s Delicatessen',
 'restaurant',
 'Iconic NYC deli open since 1888, famous for its towering pastrami sandwiches.',
 '205 E Houston St, New York, NY 10002',
 'https://maps.google.com/?q=Katzs+Deli+205+E+Houston+St',
 null,
 '["iconic","deli","lower east side","local favorite"]'),

((SELECT id FROM cities WHERE slug = 'new-york-new-jersey'),
 'Joe''s Pizza',
 'restaurant',
 'The definitive New York slice. Simple, perfect, essential.',
 '7 Carmine St, New York, NY 10014',
 'https://maps.google.com/?q=Joes+Pizza+7+Carmine+St',
 null,
 '["pizza","iconic","quick eat","village"]'),

((SELECT id FROM cities WHERE slug = 'new-york-new-jersey'),
 'Statue of Liberty',
 'attraction',
 'World-famous landmark on Liberty Island — ferry departs from Battery Park.',
 'Liberty Island, New York, NY',
 'https://maps.google.com/?q=Statue+of+Liberty',
 null,
 '["landmark","tourism","must-see","ferry"]'),

((SELECT id FROM cities WHERE slug = 'new-york-new-jersey'),
 'The High Line',
 'attraction',
 'Elevated park built on a former rail line with great views of Manhattan and the Hudson.',
 'Gansevoort St, New York, NY 10014',
 'https://maps.google.com/?q=The+High+Line+New+York',
 null,
 '["park","views","walking","free"]'),

-- =========================
-- LOS ANGELES
-- =========================
((SELECT id FROM cities WHERE slug = 'los-angeles'),
 'Tom''s Watch Bar',
 'bar',
 'Giant stadium-style sports bar with 360-degree screens — perfect for World Cup games.',
 '1011 S Figueroa St, Los Angeles, CA 90015',
 'https://maps.google.com/?q=Toms+Watch+Bar+LA+1011+S+Figueroa',
 null,
 '["sports bar","big screens","downtown","stadium district"]'),

((SELECT id FROM cities WHERE slug = 'los-angeles'),
 'The Greyhound Bar & Grill',
 'bar',
 'Long-running Highland Park bar with a casual crowd and great match-watching setup.',
 '5621 N Figueroa St, Los Angeles, CA 90042',
 'https://maps.google.com/?q=Greyhound+Bar+Grill+Los+Angeles',
 null,
 '["local","casual","highland park","neighborhood"]'),

((SELECT id FROM cities WHERE slug = 'los-angeles'),
 'EightyTwo',
 'bar',
 'Bar arcade with craft cocktails and a lively atmosphere — great pre-match spot.',
 '707 E 4th Pl, Los Angeles, CA 90013',
 'https://maps.google.com/?q=EightyTwo+Bar+Los+Angeles',
 null,
 '["arcade","bar","arts district","pregame"]'),

((SELECT id FROM cities WHERE slug = 'los-angeles'),
 'Grand Central Market',
 'restaurant',
 'Historic downtown food hall with dozens of vendors serving everything from tacos to ramen.',
 '317 S Broadway, Los Angeles, CA 90013',
 'https://maps.google.com/?q=Grand+Central+Market+LA',
 null,
 '["food hall","variety","downtown","casual"]'),

((SELECT id FROM cities WHERE slug = 'los-angeles'),
 'In-N-Out Burger',
 'restaurant',
 'California fast-food institution. The Double-Double is non-negotiable.',
 '500 Sunset Blvd, Los Angeles, CA 90028',
 'https://maps.google.com/?q=In-N-Out+Burger+Sunset+Blvd+LA',
 null,
 '["fast food","iconic","california","cheap eat"]'),

((SELECT id FROM cities WHERE slug = 'los-angeles'),
 'Hollywood Sign',
 'attraction',
 'Hike up Griffith Park for the best view of the iconic Hollywood Sign and city skyline.',
 'Griffith Park, Los Angeles, CA 90027',
 'https://maps.google.com/?q=Hollywood+Sign+Griffith+Park',
 null,
 '["landmark","hike","photo spot","free"]'),

((SELECT id FROM cities WHERE slug = 'los-angeles'),
 'Santa Monica Pier',
 'attraction',
 'Iconic pier with an amusement park, beach, and stunning Pacific Ocean sunsets.',
 '200 Santa Monica Pier, Santa Monica, CA 90401',
 'https://maps.google.com/?q=Santa+Monica+Pier',
 null,
 '["beach","pier","tourism","sunset"]'),

-- =========================
-- KANSAS CITY
-- =========================
((SELECT id FROM cities WHERE slug = 'kansas-city'),
 'No Other Pub',
 'bar',
 'Soccer-themed bar owned by Sporting KC — interactive games, cold beer, and a die-hard fan base.',
 '1370 Grand Blvd, Kansas City, MO 64106',
 'https://maps.google.com/?q=No+Other+Pub+Kansas+City',
 null,
 '["soccer","fan zone","sporting kc","interactive"]'),

((SELECT id FROM cities WHERE slug = 'kansas-city'),
 'Johnny''s Tavern',
 'bar',
 'Local favourite sports bar with a strong matchday atmosphere and affordable drinks.',
 '1310 Grand Blvd, Kansas City, MO 64106',
 'https://maps.google.com/?q=Johnnys+Tavern+Kansas+City',
 null,
 '["sports bar","local","lively","affordable"]'),

((SELECT id FROM cities WHERE slug = 'kansas-city'),
 'Joe''s Kansas City Bar-B-Que',
 'restaurant',
 'Legendary BBQ spot inside a gas station — consistently rated among the best in the US.',
 '3002 W 47th Ave, Kansas City, KS 66103',
 'https://maps.google.com/?q=Joes+Kansas+City+BBQ',
 null,
 '["bbq","iconic","must-eat","kansas city"]'),

((SELECT id FROM cities WHERE slug = 'kansas-city'),
 'Fiorella''s Jack Stack Barbecue',
 'restaurant',
 'Upscale KC BBQ institution known for burnt ends and a full bar.',
 '101 W 22nd St, Kansas City, MO 64108',
 'https://maps.google.com/?q=Jack+Stack+Barbecue+Kansas+City',
 null,
 '["bbq","upscale","burnt ends","local favorite"]'),

((SELECT id FROM cities WHERE slug = 'kansas-city'),
 'National WWI Museum & Memorial',
 'attraction',
 'World-class museum with moving exhibits and a rooftop terrace with panoramic city views.',
 '2 Memorial Dr, Kansas City, MO 64108',
 'https://maps.google.com/?q=National+WWI+Museum+Kansas+City',
 null,
 '["museum","history","landmark","views"]'),

-- =========================
-- MIAMI
-- =========================
((SELECT id FROM cities WHERE slug = 'miami'),
 'American Social',
 'bar',
 'Waterfront sports bar on the Miami River with a lively crowd and plenty of screens.',
 '690 SW 1st Ct, Miami, FL 33130',
 'https://maps.google.com/?q=American+Social+Miami+690+SW+1st+Ct',
 null,
 '["waterfront","sports","nightlife","brickell"]'),

((SELECT id FROM cities WHERE slug = 'miami'),
 'Ball & Chain',
 'bar',
 'Historic Little Havana bar with live Cuban music, tropical cocktails, and a festive vibe.',
 '1513 SW 8th St, Miami, FL 33135',
 'https://maps.google.com/?q=Ball+and+Chain+Miami',
 null,
 '["live music","cuban","culture","little havana"]'),

((SELECT id FROM cities WHERE slug = 'miami'),
 'The Fado Irish Pub',
 'bar',
 'Classic Irish pub in Brickell that reliably shows all major football matches.',
 '900 S Miami Ave, Miami, FL 33130',
 'https://maps.google.com/?q=Fado+Irish+Pub+Miami',
 null,
 '["irish pub","soccer","football","brickell"]'),

((SELECT id FROM cities WHERE slug = 'miami'),
 'Versailles Restaurant',
 'restaurant',
 'The most famous Cuban restaurant in Miami — a Little Havana institution since 1971.',
 '3555 SW 8th St, Miami, FL 33135',
 'https://maps.google.com/?q=Versailles+Restaurant+Miami',
 null,
 '["cuban","iconic","little havana","local institution"]'),

((SELECT id FROM cities WHERE slug = 'miami'),
 'Cvi.che 105',
 'restaurant',
 'Outstanding Peruvian ceviche bar — a must-visit for seafood lovers in downtown Miami.',
 '105 NE 3rd Ave, Miami, FL 33132',
 'https://maps.google.com/?q=Cviche+105+Miami',
 null,
 '["peruvian","ceviche","seafood","downtown"]'),

((SELECT id FROM cities WHERE slug = 'miami'),
 'South Beach (Ocean Drive)',
 'attraction',
 'The iconic Art Deco strip — beach, nightlife, pastel buildings, and non-stop energy.',
 'Ocean Dr, Miami Beach, FL 33139',
 'https://maps.google.com/?q=Ocean+Drive+Miami+Beach',
 null,
 '["beach","nightlife","art deco","tourism"]'),

((SELECT id FROM cities WHERE slug = 'miami'),
 'Wynwood Walls',
 'attraction',
 'World-renowned outdoor street art museum in the heart of Miami''s creative district.',
 '2516 NW 2nd Ave, Miami, FL 33127',
 'https://maps.google.com/?q=Wynwood+Walls+Miami',
 null,
 '["street art","culture","instagram","free to walk"]'),

-- =========================
-- DALLAS
-- =========================
((SELECT id FROM cities WHERE slug = 'dallas'),
 'Happiest Hour',
 'bar',
 'Multi-level rooftop bar in Uptown with great skyline views and big matchday crowds.',
 '2616 Olive St, Dallas, TX 75201',
 'https://maps.google.com/?q=Happiest+Hour+Dallas+2616+Olive+St',
 null,
 '["rooftop","views","uptown","sports"]'),

((SELECT id FROM cities WHERE slug = 'dallas'),
 'The Common Table',
 'bar',
 'Dedicated soccer bar in Uptown Dallas — the city''s spiritual home for football fans.',
 '2917 Fairmount St, Dallas, TX 75201',
 'https://maps.google.com/?q=The+Common+Table+Dallas',
 null,
 '["soccer","fan zone","uptown","football"]'),

((SELECT id FROM cities WHERE slug = 'dallas'),
 'Pecan Lodge',
 'restaurant',
 'One of Dallas''s most celebrated BBQ spots — expect a queue, but it''s worth every minute.',
 '2702 Main St, Dallas, TX 75226',
 'https://maps.google.com/?q=Pecan+Lodge+Dallas',
 null,
 '["bbq","texas","deep ellum","iconic"]'),

((SELECT id FROM cities WHERE slug = 'dallas'),
 'Mattito''s Tex-Mex',
 'restaurant',
 'Beloved local Tex-Mex with strong margaritas and reliably great fajitas.',
 '3102 Oak Lawn Ave, Dallas, TX 75219',
 'https://maps.google.com/?q=Mattitos+Dallas',
 null,
 '["tex-mex","mexican","margaritas","local"]'),

((SELECT id FROM cities WHERE slug = 'dallas'),
 'The Sixth Floor Museum at Dealey Plaza',
 'attraction',
 'Powerful museum documenting the assassination of President Kennedy in 1963.',
 '411 Elm St, Dallas, TX 75202',
 'https://maps.google.com/?q=Sixth+Floor+Museum+Dallas',
 null,
 '["history","museum","jfk","landmark"]'),

((SELECT id FROM cities WHERE slug = 'dallas'),
 'Klyde Warren Park',
 'attraction',
 'Free urban park built over a freeway — food trucks, events, and a great city atmosphere.',
 '2012 Woodall Rodgers Fwy, Dallas, TX 75201',
 'https://maps.google.com/?q=Klyde+Warren+Park+Dallas',
 null,
 '["park","free","food trucks","downtown"]'),

-- =========================
-- ATLANTA
-- =========================
((SELECT id FROM cities WHERE slug = 'atlanta'),
 'Hudson Grille',
 'bar',
 'Well-known Atlanta sports bar with dozens of screens and a reliable matchday setup.',
 '942 Peachtree St NE, Atlanta, GA 30309',
 'https://maps.google.com/?q=Hudson+Grille+Atlanta+Peachtree',
 null,
 '["sports bar","midtown","screens","fans"]'),

((SELECT id FROM cities WHERE slug = 'atlanta'),
 'Stats Brewpub',
 'bar',
 'Sports bar and brewpub near Mercedes-Benz Stadium with rotating craft taps.',
 '300 Marietta St NW, Atlanta, GA 30313',
 'https://maps.google.com/?q=Stats+Brewpub+Atlanta',
 null,
 '["craft beer","sports","stadium district","pregame"]'),

((SELECT id FROM cities WHERE slug = 'atlanta'),
 'The Varsity',
 'restaurant',
 'Atlanta icon since 1928 — the world''s largest drive-in restaurant and a city institution.',
 '61 North Ave NW, Atlanta, GA 30308',
 'https://maps.google.com/?q=The+Varsity+Atlanta',
 null,
 '["iconic","fast food","hot dogs","atlanta"]'),

((SELECT id FROM cities WHERE slug = 'atlanta'),
 'Ponce City Market',
 'restaurant',
 'Massive food hall in a restored historic building with an incredible variety of vendors.',
 '675 Ponce De Leon Ave NE, Atlanta, GA 30308',
 'https://maps.google.com/?q=Ponce+City+Market+Atlanta',
 null,
 '["food hall","variety","ponce city","midtown"]'),

((SELECT id FROM cities WHERE slug = 'atlanta'),
 'Georgia Aquarium',
 'attraction',
 'One of the largest aquariums in the world — whale sharks, beluga whales, and more.',
 '225 Baker St NW, Atlanta, GA 30313',
 'https://maps.google.com/?q=Georgia+Aquarium+Atlanta',
 null,
 '["aquarium","family","tourism","downtown"]'),

((SELECT id FROM cities WHERE slug = 'atlanta'),
 'National Center for Civil and Human Rights',
 'attraction',
 'Moving museum exploring the US civil rights movement and its global legacy.',
 '100 Ivan Allen Jr Blvd NW, Atlanta, GA 30313',
 'https://maps.google.com/?q=National+Center+Civil+Human+Rights+Atlanta',
 null,
 '["history","museum","culture","meaningful"]'),

-- =========================
-- SEATTLE
-- =========================
((SELECT id FROM cities WHERE slug = 'seattle'),
 'The George & Dragon Pub',
 'bar',
 'Classic English-style soccer pub in Fremont — the beating heart of Seattle football culture.',
 '206 N 36th St, Seattle, WA 98103',
 'https://maps.google.com/?q=George+and+Dragon+Pub+Seattle',
 null,
 '["soccer","english pub","fremont","fan culture"]'),

((SELECT id FROM cities WHERE slug = 'seattle'),
 'Fuel Sports Eats & Beats',
 'bar',
 'Capitol Hill sports bar open early for European kick-offs with a welcoming crowd.',
 '2300 1st Ave, Seattle, WA 98121',
 'https://maps.google.com/?q=Fuel+Sports+Seattle',
 null,
 '["sports bar","early games","belltown","soccer"]'),

((SELECT id FROM cities WHERE slug = 'seattle'),
 'Canlis',
 'restaurant',
 'Seattle''s most storied fine dining restaurant, perched above Lake Union with stunning views.',
 '2576 Aurora Ave N, Seattle, WA 98109',
 'https://maps.google.com/?q=Canlis+Seattle',
 null,
 '["fine dining","views","special occasion","iconic"]'),

((SELECT id FROM cities WHERE slug = 'seattle'),
 'Matt''s in the Market',
 'restaurant',
 'Beloved Pike Place Market restaurant known for fresh Pacific Northwest seafood.',
 '94 Pike St #32, Seattle, WA 98101',
 'https://maps.google.com/?q=Matts+in+the+Market+Seattle',
 null,
 '["seafood","pike place","pacific northwest","lunch"]'),

((SELECT id FROM cities WHERE slug = 'seattle'),
 'Pike Place Market',
 'attraction',
 'Historic public market since 1907 — fish throwing, fresh produce, and the original Starbucks.',
 '85 Pike St, Seattle, WA 98101',
 'https://maps.google.com/?q=Pike+Place+Market+Seattle',
 null,
 '["market","tourism","iconic","food"]'),

((SELECT id FROM cities WHERE slug = 'seattle'),
 'Space Needle',
 'attraction',
 'Seattle''s defining landmark — observation deck with 360-degree views of the city and Mt. Rainier.',
 '400 Broad St, Seattle, WA 98109',
 'https://maps.google.com/?q=Space+Needle+Seattle',
 null,
 '["landmark","views","tourism","must-see"]'),

-- =========================
-- SAN FRANCISCO
-- =========================
((SELECT id FROM cities WHERE slug = 'san-francisco'),
 'Kezar Pub',
 'bar',
 'Beloved soccer bar near Golden Gate Park, open early for every major international fixture.',
 '770 Stanyan St, San Francisco, CA 94117',
 'https://maps.google.com/?q=Kezar+Pub+San+Francisco',
 null,
 '["soccer","historic","haight","fan culture"]'),

((SELECT id FROM cities WHERE slug = 'san-francisco'),
 'The Blarney Stone',
 'bar',
 'Irish pub in the Tenderloin that reliably shows all football with an international crowd.',
 '599 Geary St, San Francisco, CA 94102',
 'https://maps.google.com/?q=Blarney+Stone+San+Francisco',
 null,
 '["irish pub","soccer","football","international fans"]'),

((SELECT id FROM cities WHERE slug = 'san-francisco'),
 'Tartine Bakery',
 'restaurant',
 'World-famous Mission District bakery — the country bread and morning buns are unmissable.',
 '600 Guerrero St, San Francisco, CA 94110',
 'https://maps.google.com/?q=Tartine+Bakery+San+Francisco',
 null,
 '["bakery","breakfast","mission","world famous"]'),

((SELECT id FROM cities WHERE slug = 'san-francisco'),
 'Swan Oyster Depot',
 'restaurant',
 'Classic SF seafood counter open since 1912 — arrive early, queue for a stool, and eat well.',
 '1517 Polk St, San Francisco, CA 94109',
 'https://maps.google.com/?q=Swan+Oyster+Depot+San+Francisco',
 null,
 '["seafood","oysters","iconic","polk street"]'),

((SELECT id FROM cities WHERE slug = 'san-francisco'),
 'Golden Gate Bridge',
 'attraction',
 'Walk or cycle the iconic bridge and take in views of the bay, Marin headlands, and the city.',
 'Golden Gate Bridge, San Francisco, CA 94129',
 'https://maps.google.com/?q=Golden+Gate+Bridge+San+Francisco',
 null,
 '["landmark","tourism","iconic","free to walk"]'),

((SELECT id FROM cities WHERE slug = 'san-francisco'),
 'Alcatraz Island',
 'attraction',
 'The infamous island federal prison — book ferry tickets well in advance.',
 'Alcatraz Island, San Francisco, CA',
 'https://maps.google.com/?q=Alcatraz+Island+San+Francisco',
 null,
 '["history","island","tourism","book ahead"]'),

-- =========================
-- PHILADELPHIA
-- =========================
((SELECT id FROM cities WHERE slug = 'philadelphia'),
 'Xfinity Live!',
 'bar',
 'Massive sports and entertainment complex in the stadium district — multiple bars under one roof.',
 '1100 Pattison Ave, Philadelphia, PA 19148',
 'https://maps.google.com/?q=Xfinity+Live+Philadelphia',
 null,
 '["sports complex","stadium district","fan zone","large venue"]'),

((SELECT id FROM cities WHERE slug = 'philadelphia'),
 'Chickie''s & Pete''s',
 'bar',
 'Philadelphia sports bar institution famous for its crab fries and passionate local crowd.',
 '1526 Packer Ave, Philadelphia, PA 19145',
 'https://maps.google.com/?q=Chickies+Petes+Philadelphia',
 null,
 '["sports bar","crab fries","local institution","south philly"]'),

((SELECT id FROM cities WHERE slug = 'philadelphia'),
 'Pat''s King of Steaks',
 'restaurant',
 'The original Philly cheesesteak since 1930 — the South Philly rivalry with Geno''s next door is real.',
 '1237 E Passyunk Ave, Philadelphia, PA 19147',
 'https://maps.google.com/?q=Pats+King+of+Steaks+Philadelphia',
 null,
 '["cheesesteak","iconic","south philly","must-eat"]'),

((SELECT id FROM cities WHERE slug = 'philadelphia'),
 'Reading Terminal Market',
 'restaurant',
 'Historic indoor market with Amish stalls, local food vendors, and some of the best lunch in the city.',
 '51 N 12th St, Philadelphia, PA 19107',
 'https://maps.google.com/?q=Reading+Terminal+Market+Philadelphia',
 null,
 '["food market","variety","historic","center city"]'),

((SELECT id FROM cities WHERE slug = 'philadelphia'),
 'Liberty Bell Center',
 'attraction',
 'The enduring symbol of American independence — free entry, easy to combine with Independence Hall.',
 '526 Market St, Philadelphia, PA 19106',
 'https://maps.google.com/?q=Liberty+Bell+Philadelphia',
 null,
 '["history","landmark","free","old city"]'),

((SELECT id FROM cities WHERE slug = 'philadelphia'),
 'Rocky Steps at the Philadelphia Museum of Art',
 'attraction',
 'Run the steps, raise your fists. One of the most iconic movie locations in the world.',
 '2600 Benjamin Franklin Pkwy, Philadelphia, PA 19130',
 'https://maps.google.com/?q=Philadelphia+Museum+of+Art+Rocky+Steps',
 null,
 '["iconic","photo spot","rocky","free to visit"]'),

-- =========================
-- BOSTON
-- =========================
((SELECT id FROM cities WHERE slug = 'boston'),
 'The Greatest Bar',
 'bar',
 'Four floors of sports bars, clubs, and lounges near TD Garden — always busy on matchday.',
 '262 Friend St, Boston, MA 02114',
 'https://maps.google.com/?q=The+Greatest+Bar+Boston',
 null,
 '["sports bar","td garden","multi-level","fans"]'),

((SELECT id FROM cities WHERE slug = 'boston'),
 'Banners Kitchen & Tap',
 'bar',
 'Upscale sports bar connected to TD Garden, great for pre-match drinks with strong food.',
 '82 Causeway St, Boston, MA 02114',
 'https://maps.google.com/?q=Banners+Kitchen+Tap+Boston',
 null,
 '["sports bar","upscale","td garden","pregame"]'),

((SELECT id FROM cities WHERE slug = 'boston'),
 'Union Oyster House',
 'restaurant',
 'America''s oldest restaurant in continuous service since 1826 — the clam chowder is legendary.',
 '41 Union St, Boston, MA 02108',
 'https://maps.google.com/?q=Union+Oyster+House+Boston',
 null,
 '["seafood","historic","clam chowder","faneuil hall"]'),

((SELECT id FROM cities WHERE slug = 'boston'),
 'Regina Pizzeria',
 'restaurant',
 'Boston''s most beloved pizza since 1926 — thin crust, old school, and always a queue.',
 '11½ Thacher St, Boston, MA 02113',
 'https://maps.google.com/?q=Regina+Pizzeria+Boston+North+End',
 null,
 '["pizza","north end","historic","iconic"]'),

((SELECT id FROM cities WHERE slug = 'boston'),
 'Freedom Trail',
 'attraction',
 'A 2.5-mile walking trail connecting 16 historic sites through the heart of colonial Boston.',
 'Boston Common, Boston, MA 02108',
 'https://maps.google.com/?q=Freedom+Trail+Boston',
 null,
 '["history","walking tour","free","landmarks"]'),

((SELECT id FROM cities WHERE slug = 'boston'),
 'Fenway Park',
 'attraction',
 'The oldest ballpark in Major League Baseball — tours available, and a must-see for any sports fan.',
 '4 Jersey St, Boston, MA 02215',
 'https://maps.google.com/?q=Fenway+Park+Boston',
 null,
 '["sports","baseball","historic","tours"]'),

-- =========================
-- HOUSTON
-- =========================
((SELECT id FROM cities WHERE slug = 'houston'),
 'Pitch 25',
 'bar',
 'Houston''s premier soccer bar with a mini five-a-side pitch, huge screens, and craft beer.',
 '2120 Walker St, Houston, TX 77003',
 'https://maps.google.com/?q=Pitch+25+Houston',
 null,
 '["soccer","bar","fan zone","east downtown"]'),

((SELECT id FROM cities WHERE slug = 'houston'),
 'The Pub Houston',
 'bar',
 'British-style pub near Minute Maid Park — open early for European matches with a loyal football crowd.',
 '519 Main St, Houston, TX 77002',
 'https://maps.google.com/?q=The+Pub+Houston+519+Main+St',
 null,
 '["british pub","soccer","football","downtown"]'),

((SELECT id FROM cities WHERE slug = 'houston'),
 'Truth BBQ',
 'restaurant',
 'Consistently rated among the very best BBQ in Texas — the brisket is worth the wait.',
 '110 S Heights Blvd, Houston, TX 77007',
 'https://maps.google.com/?q=Truth+BBQ+Houston',
 null,
 '["bbq","texas","brisket","heights"]'),

((SELECT id FROM cities WHERE slug = 'houston'),
 'Ninfa''s on Navigation',
 'restaurant',
 'The original Ninfa''s — credited with inventing the fajita in 1973. A Houston dining landmark.',
 '2704 Navigation Blvd, Houston, TX 77003',
 'https://maps.google.com/?q=Ninfas+on+Navigation+Houston',
 null,
 '["tex-mex","fajitas","iconic","east end"]'),

((SELECT id FROM cities WHERE slug = 'houston'),
 'Space Center Houston',
 'attraction',
 'The official visitor center for NASA''s Johnson Space Center — rockets, missions, and astronaut history.',
 '1601 NASA Pkwy, Houston, TX 77058',
 'https://maps.google.com/?q=Space+Center+Houston',
 null,
 '["nasa","space","museum","tourism"]'),

((SELECT id FROM cities WHERE slug = 'houston'),
 'Museum of Fine Arts Houston',
 'attraction',
 'One of the largest art museums in the US with an outstanding permanent collection.',
 '1001 Bissonnet St, Houston, TX 77005',
 'https://maps.google.com/?q=Museum+Fine+Arts+Houston',
 null,
 '["art","museum","museum district","culture"]');